### ISSUE TITLE
"Vuositasolla vähennettävä vielä" seems to be wrong

### ISSUE THREAD

**Issue by jtuomist** [juyrjola/ghg-helsinki#1]
Based on the graph, the total emissions are ca. 2700 kton in 2017. The target is ca 3500*0.2=700, so there is ca 2000 kton to go. However, the UI says 3 814 000 t CO2e. Does this come from the code or is it just a placeholder?

**Comment by juyrjola** [comment]
Oops, looks like the number from the whole metropolitan area was used. The current number does not come from the model, but it is defined in the UI code directly: https://github.com/City-of-Helsinki/cnh-ui/blob/master/components/IndexHero.js#L44

Maybe you'd like to submit a PR to the UI? :-)

**Comment by jtuomist** [comment]
Now it is correct. Maybe you should close this issue.

**Comment by jtuomist** [comment]
OK, it seems that also I can do it.
